version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: payetonkawa-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - db_data_api:/var/lib/postgresql/data
    networks:
      - payetonkawa

  api-produits:
    build: .
    container_name: api-produits
    ports:
      - "8080:8080"
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - payetonkawa

volumes:
  db_data_api:

networks:
  payetonkawa:
