# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://produits-db:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- RabbitMQ ---
rabbitmq.product.queue=products.queue
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.product.exchange=products.exchange
rabbitmq.product.queue=products.queue
rabbitmq.product.routing-key=products.key


# URL du realm Keycloak pour valider les JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8083/realms/paye-ton-kawa
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8083/realms/ton-realm/protocol/openid-connect/certs

server.port=8081



